<a href="https://colab.research.google.com/github/sneha-kolli/Machine_Learning-and-Data_Science/blob/main/Cancer_Prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df=pd.read_csv('survey_lung_cancer.csv')
print('data imported')

data imported


In [4]:
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [5]:
df.tail()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
304         2                    2                      2           1   
305         2                    2                      1           2   
306         2                    1                      1           2   
307         2                    2                      1           2   
308         1                    1                      2           1   

    LUNG_CANCER  
304         YES  
305         YES  
306         YES  
307         YES  
308         YES

In [6]:
df.shape

(309, 16)

In [7]:
df.describe(include='all') # it helps to print the summary all the attributes including categorical data

GENDER         AGE     SMOKING  YELLOW_FINGERS     ANXIETY  \
count     309  309.000000  309.000000      309.000000  309.000000   
unique      2         NaN         NaN             NaN         NaN   
top         M         NaN         NaN             NaN         NaN   
freq      162         NaN         NaN             NaN         NaN   
mean      NaN   62.673139    1.563107        1.569579    1.498382   
std       NaN    8.210301    0.496806        0.495938    0.500808   
min       NaN   21.000000    1.000000        1.000000    1.000000   
25%       NaN   57.000000    1.000000        1.000000    1.000000   
50%       NaN   62.000000    2.000000        2.000000    1.000000   
75%       NaN   69.000000    2.000000        2.000000    2.000000   
max       NaN   87.000000    2.000000        2.000000    2.000000   

        PEER_PRESSURE  CHRONIC DISEASE    FATIGUE     ALLERGY     WHEEZING  \
count      309.000000       309.000000  309.000000  309.000000  309.000000   
unique            NaN              NaN         NaN         NaN         NaN   
top               NaN              NaN         NaN         NaN         NaN   
freq              NaN              NaN         NaN         NaN         NaN   
mean         1.501618         1.504854    1.673139    1.556634    1.556634   
std          0.500808         0.500787    0.469827    0.497588    0.497588   
min          1.000000         1.000000    1.000000    1.000000    1.000000   
25%          1.000000         1.000000    1.000000    1.000000    1.000000   
50%          2.000000         2.000000    2.000000    2.000000    2.000000   
75%          2.000000         2.000000    2.000000    2.000000    2.000000   
max          2.000000         2.000000    2.000000    2.000000    2.000000   

        ALCOHOL CONSUMING    COUGHING  SHORTNESS OF BREATH  \
count          309.000000  309.000000           309.000000   
unique                NaN         NaN                  NaN   
top                   NaN         NaN                  NaN   
freq                  NaN         NaN                  NaN   
mean             1.556634    1.579288             1.640777   
std              0.497588    0.494474             0.480551   
min              1.000000    1.000000             1.000000   
25%              1.000000    1.000000             1.000000   
50%              2.000000    2.000000             2.000000   
75%              2.000000    2.000000             2.000000   
max              2.000000    2.000000             2.000000   

        SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
count              309.000000  309.000000         309  
unique                    NaN         NaN           2  
top                       NaN         NaN         YES  
freq                      NaN         NaN         270  
mean                 1.469256    1.556634         NaN  
std                  0.499863    0.497588         NaN  
min                  1.000000    1.000000         NaN  
25%                  1.000000    1.000000         NaN  
50%                  1.000000    2.000000         NaN  
75%                  2.000000    2.000000         NaN  
max                  2.000000    2.000000         NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64 
 2   SMOKING                309 non-null    int64 
 3   YELLOW_FINGERS         309 non-null    int64 
 4   ANXIETY                309 non-null    int64 
 5   PEER_PRESSURE          309 non-null    int64 
 6   CHRONIC DISEASE        309 non-null    int64 
 7   FATIGUE                309 non-null    int64 
 8   ALLERGY                309 non-null    int64 
 9   WHEEZING               309 non-null    int64 
 10  ALCOHOL CONSUMING      309 non-null    int64 
 11  COUGHING               309 non-null    int64 
 12  SHORTNESS OF BREATH    309 non-null    int64 
 13  SWALLOWING DIFFICULTY  309 non-null    int64 
 14  CHEST PAIN             309 non-null    int64 
 15  LUNG_CANCER            

Let's start taking off the unnecessary columns from the dataset

In [9]:
df=df.drop(columns=['ALLERGY '])

In [10]:
df=df.drop(columns=['PEER_PRESSURE'])

In [11]:
df=df.drop(columns=['CHRONIC DISEASE'])

In [12]:
df=df.drop(columns=['ALCOHOL CONSUMING'])

In [13]:
df=df.drop(columns=['YELLOW_FINGERS'])

In [14]:
df.head()

GENDER  AGE  SMOKING  ANXIETY  FATIGUE   WHEEZING  COUGHING  \
0      M   69        1        2         2         2         2   
1      M   74        2        1         2         1         1   
2      F   59        1        1         2         2         2   
3      M   63        2        2         1         1         1   
4      F   63        1        1         1         2         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [15]:
df=pd.get_dummies(df) # this command helps us to create duplicate columns for the categorical variables.
df.head()

AGE  SMOKING  ANXIETY  FATIGUE   WHEEZING  COUGHING  SHORTNESS OF BREATH  \
0   69        1        2         2         2         2                    2   
1   74        2        1         2         1         1                    2   
2   59        1        1         2         2         2                    2   
3   63        2        2         1         1         1                    1   
4   63        1        1         1         2         2                    2   

   SWALLOWING DIFFICULTY  CHEST PAIN  GENDER_F  GENDER_M  LUNG_CANCER_NO  \
0                      2           2         0         1               0   
1                      2           2         0         1               0   
2                      1           2         1         0               1   
3                      2           2         0         1               1   
4                      1           1         1         0               1   

   LUNG_CANCER_YES  
0                1  
1                1  
2                0  
3                0  
4                0

Let's drop one of the duplicate column as one indicates the specific so we can assume the other one with great probability.

In [16]:
df=df.drop(columns=['GENDER_M'])

In [17]:
df=df.drop(columns=['LUNG_CANCER_NO'])

In [18]:
df.head()

AGE  SMOKING  ANXIETY  FATIGUE   WHEEZING  COUGHING  SHORTNESS OF BREATH  \
0   69        1        2         2         2         2                    2   
1   74        2        1         2         1         1                    2   
2   59        1        1         2         2         2                    2   
3   63        2        2         1         1         1                    1   
4   63        1        1         1         2         2                    2   

   SWALLOWING DIFFICULTY  CHEST PAIN  GENDER_F  LUNG_CANCER_YES  
0                      2           2         0                1  
1                      2           2         0                1  
2                      1           2         1                0  
3                      2           2         0                0  
4                      1           1         1                0

Declaring the target and predicting variables

In [19]:
target=df['LUNG_CANCER_YES']
predictor=df.drop(columns=['LUNG_CANCER_YES'])

In [20]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
predictor=ss.fit_transform(predictor)

In [21]:
predictor[5]

array([ 1.50382491, -1.13529242, -0.99676897,  0.6968335 ,  0.892475  ,
        0.85220712,  0.74873631, -0.94029056, -1.12047956,  1.04978132])

In [22]:
ss.mean_

array([62.67313916,  1.5631068 ,  1.49838188,  1.67313916,  1.5566343 ,
        1.57928803,  1.6407767 ,  1.46925566,  1.5566343 ,  0.47572816])

# Let's test with different models

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,Y_train,Y_test = train_test_split(predictor,target,test_size=0.2,random_state=0)

In [25]:
X_train

array([[-1.42407363,  0.88083033,  1.0032415 , ...,  1.06350105,
        -1.12047956,  1.04978132],
       [ 1.13783759,  0.88083033,  1.0032415 , ...,  1.06350105,
         0.892475  , -0.95257934],
       [-0.44810745,  0.88083033, -0.99676897, ..., -0.94029056,
        -1.12047956, -0.95257934],
       ...,
       [-1.42407363,  0.88083033,  1.0032415 , ...,  1.06350105,
        -1.12047956,  1.04978132],
       [ 0.16187141,  0.88083033, -0.99676897, ...,  1.06350105,
         0.892475  ,  1.04978132],
       [-0.81409477, -1.13529242, -0.99676897, ..., -0.94029056,
        -1.12047956, -0.95257934]])

In [26]:
X_test

array([[ 0.6498545 , -1.13529242,  1.0032415 , -1.43506304,  0.892475  ,
        -1.17342366, -1.33558369,  1.06350105, -1.12047956,  1.04978132],
       [ 0.16187141,  0.88083033,  1.0032415 ,  0.6968335 , -1.12047956,
         0.85220712,  0.74873631, -0.94029056,  0.892475  , -0.95257934],
       [-0.08212013, -1.13529242, -0.99676897, -1.43506304, -1.12047956,
         0.85220712,  0.74873631,  1.06350105,  0.892475  , -0.95257934],
       [ 0.6498545 , -1.13529242,  1.0032415 , -1.43506304, -1.12047956,
        -1.17342366, -1.33558369, -0.94029056, -1.12047956, -0.95257934],
       [ 0.52785873,  0.88083033,  1.0032415 ,  0.6968335 , -1.12047956,
        -1.17342366, -1.33558369, -0.94029056, -1.12047956,  1.04978132],
       [ 0.28386719,  0.88083033,  1.0032415 ,  0.6968335 ,  0.892475  ,
         0.85220712,  0.74873631,  1.06350105, -1.12047956,  1.04978132],
       [-0.93609054,  0.88083033,  1.0032415 ,  0.6968335 ,  0.892475  ,
         0.85220712,  0.74873631,  1.06350105

In [27]:
Y_train

7      1
45     1
97     1
92     1
198    1
      ..
251    1
192    1
117    1
47     1
172    1
Name: LUNG_CANCER_YES, Length: 247, dtype: uint8

In [28]:
Y_test

63     1
231    1
167    1
159    0
189    1
      ..
34     0
250    1
33     1
21     1
103    1
Name: LUNG_CANCER_YES, Length: 62, dtype: uint8

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
lr = LogisticRegression()

In [31]:
lr.fit(X_train,Y_train)

LogisticRegression()

In [32]:
y_pred = lr.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
print(accuracy_score(y_pred,Y_test))

0.9032258064516129


# Support Vector Machine(SVM)

SVM(kernel = 'rbf/linear'), Naive Bayes , KNN , Decision Tree(criterion = 'gini\entropy') , Random Forest (criterion = 'gini\entropy')

In [35]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [36]:
clf = SVC(kernel="linear")

clf.fit(X_train,Y_train)


SVC(kernel='linear')

In [37]:
y_pred = clf.predict(X_test)

In [39]:
print(accuracy_score(y_pred,Y_test))

0.8387096774193549


In [40]:
clf1 = SVC(kernel="rbf")

clf1.fit(X_train,Y_train)

SVC()

In [41]:
y_pred = clf1.predict(X_test)

In [42]:
print(accuracy_score(y_pred,Y_test))

0.8548387096774194


# Naive Bayes

In [43]:
from sklearn.naive_bayes import GaussianNB

In [44]:
gnb = GaussianNB()

In [45]:
gnb.fit(X_train,Y_train)

GaussianNB()

In [46]:
y_pred = gnb.predict(X_test)

In [47]:
print(accuracy_score(y_pred,Y_test))

0.8870967741935484


KNN

In [48]:
from sklearn.neighbors import KNeighborsClassifier

In [73]:
knn = KNeighborsClassifier(n_neighbors=3)

In [74]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [75]:
y_pred = knn.predict(X_test)

In [76]:
print(accuracy_score(y_pred,Y_test))

0.8709677419354839


# Decision Tree (gini)

In [77]:
from sklearn.tree import DecisionTreeClassifier

In [80]:
clf_gini = DecisionTreeClassifier(criterion = "gini")
clf_gini.fit(X_train, Y_train)

DecisionTreeClassifier()

In [81]:
y_pred = clf_gini.predict(X_test)

In [82]:
print(accuracy_score(y_pred,Y_test))

0.8064516129032258


## Decision Tree (Entropy)

In [83]:
clf_gini = DecisionTreeClassifier(criterion = "entropy")
clf_gini.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy')

In [84]:
y_pred = clf_gini.predict(X_test)

In [85]:
print(accuracy_score(y_pred,Y_test))

0.8064516129032258


## Random Forest (gini)

In [86]:
from sklearn.ensemble import RandomForestClassifier

In [87]:
rfc = RandomForestClassifier(criterion='gini')
rfc.fit(X_train,Y_train)

RandomForestClassifier()

In [88]:
y_pred = rfc.predict(X_test)

In [89]:
print(accuracy_score(y_pred,Y_test))

0.8709677419354839


# Random Forest (Entropy)

In [90]:
rfc = RandomForestClassifier(criterion='entropy')
rfc.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy')

In [91]:
y_pred = rfc.predict(X_test)

In [92]:
print(accuracy_score(y_pred,Y_test))

0.8709677419354839


In [93]:
from sklearn.metrics import classification_report

In [94]:
print(classification_report(y_pred,Y_test))

              precision    recall  f1-score   support

           0       0.30      0.75      0.43         4
           1       0.98      0.88      0.93        58

    accuracy                           0.87        62
   macro avg       0.64      0.81      0.68        62
weighted avg       0.94      0.87      0.90        62



Let's apply GridSearchCV to find the best accuracy and best parameters.

In [96]:
from time import time
parameters = {'penalty' : ['l1', 'l2', 'elasticnet', None],
              'solver' : ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
              'max_iter' : [100, 200, 300, 400, 500],
              }
#we are checking in the different variation of numerical values
#in the parameters of Logistic Regression

from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator = lr, # Make sure classifier points to the LR model
                           param_grid = parameters,
                           scoring = "accuracy",
                           cv = 10,#from k-fold validation
                           n_jobs = -1)#to use the entire core of the machine

t0 = time()#just to check how much time it takes to excute the program
grid_search = grid_search.fit(X_train, Y_train)
t1 = time()
print("Took %0.2f seconds" % (t1 - t0))

rf_best_accuracy = grid_search.best_score_
rf_best_parameters = grid_search.best_params_
rf_best_accuracy, rf_best_parameters

Took 5.92 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
550 fits failed out of a total of 1200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: So

(0.8741666666666668, {'max_iter': 100, 'penalty': 'l2', 'solver': 'lbfgs'})