# **Customer Purchase Prediction & Effect of Micro-Numerosity**

In [1]:
#import the required libraries
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Customer%20Purchase.csv')

In [3]:
df

Customer ID  Age  Gender Education   Review Purchased
0          1021   30  Female    School  Average        No
1          1022   68  Female        UG     Poor        No
2          1023   70  Female        PG     Good        No
3          1024   72  Female        PG     Good        No
4          1025   16  Female        UG  Average        No
5          1026   31  Female    School  Average       Yes
6          1027   18    Male    School     Good        No
7          1028   60  Female    School     Poor       Yes
8          1029   65  Female        UG  Average        No
9          1030   74    Male        UG     Good       Yes
10         1031   98  Female        UG     Good       Yes
11         1032   74    Male        UG     Good       Yes
12         1033   51    Male    School     Poor        No
13         1034   57  Female    School  Average        No
14         1035   15    Male        PG     Poor       Yes
15         1036   75    Male        UG     Poor        No
16         1037   59    Male        UG     Poor       Yes
17         1038   22  Female        UG     Poor       Yes
18         1039   19    Male    School     Good        No
19         1040   97    Male        PG     Poor       Yes
20         1041   57  Female    School  Average       Yes
21         1042   32    Male        PG  Average        No
22         1043   18  Female        PG     Poor       Yes
23         1044   96  Female    School     Good        No
24         1045   16  Female        PG  Average       Yes
25         1046   57  Female    School     Good        No
26         1047   53  Female        PG     Poor        No
27         1048   69  Female        PG     Poor        No
28         1049   48    Male    School     Poor        No
29         1050   83  Female        UG  Average       Yes
30         1051   73    Male        UG  Average        No
31         1052   22  Female    School     Poor       Yes
32         1053   92    Male        UG  Average       Yes
33         1054   89  Female        PG     Good       Yes
34         1055   86    Male    School  Average        No
35         1056   74    Male    School     Poor       Yes
36         1057   34  Female        UG     Good       Yes
37         1058   94    Male        PG  Average       Yes
38         1059   45  Female    School     Good        No
39         1060   76    Male        PG     Poor        No
40         1061   39    Male    School     Good        No
41         1062   23    Male        PG     Good       Yes
42         1063   30  Female        PG     Good       Yes
43         1064   27    Male        PG     Poor        No
44         1065   77  Female        UG  Average        No
45         1066   61    Male        PG     Poor       Yes
46         1067   64  Female        PG     Poor        No
47         1068   38  Female        PG     Good       Yes
48         1069   39  Female        UG     Good       Yes
49         1070   25  Female        UG     Good        No

In [4]:
df.head()

Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [5]:
df.tail()

Customer ID  Age  Gender Education Review Purchased
45         1066   61    Male        PG   Poor       Yes
46         1067   64  Female        PG   Poor        No
47         1068   38  Female        PG   Good       Yes
48         1069   39  Female        UG   Good       Yes
49         1070   25  Female        UG   Good        No

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer ID  50 non-null     int64 
 1   Age          50 non-null     int64 
 2   Gender       50 non-null     object
 3   Education    50 non-null     object
 4   Review       50 non-null     object
 5   Purchased    50 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.5+ KB


In [7]:
df.describe()

Customer ID        Age
count     50.00000  50.000000
mean    1045.50000  54.160000
std       14.57738  25.658161
min     1021.00000  15.000000
25%     1033.25000  30.250000
50%     1045.50000  57.000000
75%     1057.75000  74.000000
max     1070.00000  98.000000

In [8]:
df.describe(include='all')

Customer ID        Age  Gender Education Review Purchased
count      50.00000  50.000000      50        50     50        50
unique          NaN        NaN       2         3      3         2
top             NaN        NaN  Female        PG   Poor        No
freq            NaN        NaN      29        18     18        26
mean     1045.50000  54.160000     NaN       NaN    NaN       NaN
std        14.57738  25.658161     NaN       NaN    NaN       NaN
min      1021.00000  15.000000     NaN       NaN    NaN       NaN
25%      1033.25000  30.250000     NaN       NaN    NaN       NaN
50%      1045.50000  57.000000     NaN       NaN    NaN       NaN
75%      1057.75000  74.000000     NaN       NaN    NaN       NaN
max      1070.00000  98.000000     NaN       NaN    NaN       NaN

In [10]:
df.columns.tolist()

['Customer ID', 'Age', 'Gender', 'Education', 'Review', 'Purchased']

In [9]:
#let's split the data

Y = df['Purchased']

In [38]:
X = df[['Gender', 'Education', 'Review']]

In [53]:
Y.shape

(50,)

In [54]:
X.shape

(50, 3)

In [55]:
from sklearn.model_selection import train_test_split

In [69]:
#let's split the data into the train and test

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=42)

In [70]:
X_train.shape

(37, 3)

In [71]:
X_test.shape

(13, 3)

In [72]:
Y_train.shape

(37,)

In [73]:
Y_test.shape

(13,)

In [74]:
#let's choose a model

from sklearn.linear_model import LogisticRegression

In [75]:
LR = LogisticRegression()

In [36]:
LR.fit(X_train,Y_train)

ValueError: ignored

In [50]:
#as we can see that it is throwing error becausse the data is completely in string format but as we all know that the data it processes is numerical

In [67]:
X.replace({'Review':{'Poor':0,'Average':1,'Good':2}},inplace=True)
X.replace({'Education':{'School':0,'UG':1,'PG':2}},inplace=True)
X.replace({'Gender':{'Male':0,'Female':1}},inplace=True)

<ipython-input-67-fb01ffda56ad>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.replace({'Review':{'Poor':0,'Average':1,'Good':2}},inplace=True)
<ipython-input-67-fb01ffda56ad>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.replace({'Education':{'School':0,'UG':1,'PG':2}},inplace=True)
<ipython-input-67-fb01ffda56ad>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentati

In [76]:
LR.fit(X_train,Y_train)

LogisticRegression()

In [78]:
LR.intercept_

array([-0.44096004])

In [79]:
LR.coef_

array([[ 0.21822971,  0.25434065, -0.00365736]])

In [77]:
y_predict = LR.predict(X_test)

In [80]:
y_predict

array(['No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes',
       'No', 'Yes', 'Yes'], dtype=object)

In [81]:
#as it is a classification problem let's see it's accuracy by following metrics

In [82]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [83]:
print(classification_report(Y_test,y_predict))

              precision    recall  f1-score   support

          No       0.80      0.57      0.67         7
         Yes       0.62      0.83      0.71         6

    accuracy                           0.69        13
   macro avg       0.71      0.70      0.69        13
weighted avg       0.72      0.69      0.69        13



In [84]:
print(accuracy_score(Y_test,y_predict))

0.6923076923076923


In [85]:
print(confusion_matrix(Y_test,y_predict))

[[4 3]
 [1 5]]
