<a href="https://colab.research.google.com/github/sneha-kolli/Machine_Learning-and-Data_Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To install the package numpy you can make use of the following statement.

In [85]:
# pip install numpy
# syntax : pip install package_name/module_name

To import the numpy package and instead of using the name numpy we can make use of shorter forms for better experience.

In [86]:
import numpy as np

In [87]:
x = np.array([1,2,3]) # it basically takes a list and successfully makes into  a array.

In [88]:
print(x)

[1 2 3]


In [89]:
type(x) #ndarray here means n-dimensional array.here the value of n can be any value.

numpy.ndarray

In [90]:
print(x[2])

3


In [91]:
y = np.array([1,2,3.5,4.3,5.8]) # here we tried to declare an array with floating values which really made other values in the array as floating point values as well.

In [92]:
print(y)

[1.  2.  3.5 4.3 5.8]


In [93]:
print(type(y))

<class 'numpy.ndarray'>


In [94]:
print(y[1]) # here it shows

2.0


In [95]:
print(y[4])

5.8


In [96]:
z = np.array([1,2,3,5.6,8.3,"python","DS"])

In [97]:
print(z) # it conevrts the array into string one.

['1' '2' '3' '5.6' '8.3' 'python' 'DS']


In [98]:
print(type(z))

<class 'numpy.ndarray'>


In [99]:
print(z[3])
print(type(z[3]))

5.6
<class 'numpy.str_'>


In [100]:
print(z[-1])
print(type(z[-1]))

DS
<class 'numpy.str_'>


In [101]:
a = [[1,2,3],[4,5,6],[7,8,9]]

In [102]:
arr = np.array(a)

In [103]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
print(type(arr))

<class 'numpy.ndarray'>


In [105]:
arr[0]

array([1, 2, 3])

In [106]:
arr[0][0]

1

In [107]:
arr[0,0]

1

np.arange() is a function that helps the user to create a sequence by providing the start,end,step.

In [108]:
b = np.arange(60)

In [109]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [110]:
print(b.shape)

(60,)


In [111]:
b.reshape(10,6) # 1-array with 10-rows and 6-columns

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [112]:
b.reshape(3,4,5) # 3-tables,4-rows,5-columns

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [113]:
b.reshape(3,2,2,5)

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]],


       [[[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]])

In [114]:
b # this doesn't store the changes well.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [115]:
b = b.reshape(3,4,5)

In [116]:
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [117]:
#to make it flatten we can make use of
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [118]:
b = b.reshape(10,6)

In [119]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [120]:
c = np.ones((10,6))

In [121]:
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [122]:
d = np.zeros((10,6))

In [123]:
print(d)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [124]:
print(d+1)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [125]:
print(c+d)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [126]:
d+b

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40., 41.],
       [42., 43., 44., 45., 46., 47.],
       [48., 49., 50., 51., 52., 53.],
       [54., 55., 56., 57., 58., 59.]])

In [127]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [128]:
e = d+b

In [129]:
print(e)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]
 [36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47.]
 [48. 49. 50. 51. 52. 53.]
 [54. 55. 56. 57. 58. 59.]]


In [130]:
e.mean()

29.5

In [131]:
e.std() # The standard deviation is a measure of how much the individual elements in the array deviate from the mean (average) value. It provides a measure of the spread or dispersion of the data.

17.318102282486574

In [132]:
e.var() #The variance is the square of the standard deviation and also measures the spread or dispersion of the data. It quantifies how much the elements differ from the mean.


299.9166666666667

In [134]:
np.mean(e)

29.5

In [136]:
e.mean(axis=0) # row mean

array([27., 28., 29., 30., 31., 32.])

In [137]:
e.mean(axis=1) # for columns

array([ 2.5,  8.5, 14.5, 20.5, 26.5, 32.5, 38.5, 44.5, 50.5, 56.5])

In [138]:
np.pi

3.141592653589793

In [139]:
np.min(e)

0.0

In [140]:
np.max(e)

59.0

In [141]:
np.abs(-6)

6

In [143]:
np.log(10) # here the base is 'e'

2.302585092994046

In [144]:
np.log10(100)

2.0

In [145]:
np.log2(8)

3.0

In [146]:
np.sin(2) #radian

0.9092974268256817

In [148]:
np.sin(e)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
        -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332,
        -0.96139749],
       [-0.75098725,  0.14987721,  0.91294525,  0.83665564, -0.00885131,
        -0.8462204 ],
       [-0.90557836, -0.13235175,  0.76255845,  0.95637593,  0.27090579,
        -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267],
       [-0.99177885, -0.64353813,  0.29636858,  0.96379539,  0.74511316,
        -0.15862267],
       [-0.91652155, -0.83177474,  0.01770193,  0.85090352,  0.90178835,
         0.12357312],
       [-0.76825466, -0.95375265, -0.26237485,  0.67022918,  0.98662759,
         0.39592515],
       [-0.55878905, -0.99975517, -0.521551  ,  0.43616476,  0.99287265,
         0.63673801]])

In [149]:
np.cos(2)

-0.4161468365471424

In [150]:
np.cos(e)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
         0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791, -0.95765948,
        -0.27516334],
       [ 0.66031671,  0.98870462,  0.40808206, -0.54772926, -0.99996083,
        -0.53283302],
       [ 0.42417901,  0.99120281,  0.64691932, -0.29213881, -0.96260587,
        -0.74805753],
       [ 0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
        -0.90369221],
       [-0.12796369,  0.76541405,  0.95507364,  0.26664293, -0.66693806,
        -0.98733928],
       [-0.39998531,  0.5551133 ,  0.99984331,  0.52532199, -0.43217794,
        -0.99233547],
       [-0.64014434,  0.30059254,  0.96496603,  0.7421542 , -0.16299078,
        -0.91828279],
       [-0.82930983,  0.02212676,  0.85322011,  0.89986683,  0.11918014,
        -0.77108022]])

In [151]:
np.random.rand()

0.7064865851795628

In [153]:
np.random.rand(10,2)

array([[0.58763731, 0.41639879],
       [0.20781931, 0.09643625],
       [0.15791843, 0.53233635],
       [0.80601451, 0.22675253],
       [0.94241986, 0.05131784],
       [0.13758322, 0.05654603],
       [0.53799645, 0.35962955],
       [0.02596504, 0.57971888],
       [0.70035331, 0.0817057 ],
       [0.02101972, 0.1550157 ]])

In [154]:
np.random.randint(10,20,10) # it is an array with the lb = 10 and ub = 20 and create an array of size 10.

array([13, 18, 18, 13, 11, 15, 16, 13, 14, 16])